name: 'Check Version'
description: 'Check version number in version file versus latest published version tag'
inputs:
  version-file:
    description: 'Path to the version file'
    required: true
    default: '.VERSION'
  check-only:
    description: 'If "yes", will only check if version in version-file is valid; if "no" will also push a new tag (default: "no")'
    required: false
    default: 'no'
  read-only:
    description: 'If "yes", will only read the version-file without any other check (default: "no")'
    required: false
    default: 'no'
outputs:
  last-version:
    description: 'Last version tag published'
    value: ${{ steps.step1.outputs.last-version }}
  new-version:
    description: 'New version contained in the version file'
    value: ${{ steps.step2.outputs.new-version }}
runs:
  using: "composite"
  steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Check input
        run: |
          if [[ (${{ inputs.check-only }} != "yes") && (${{ inputs.check-only }} != "no") ]]; then
            echo "::error::'${{ inputs.check-only }}' is not a valid input (should be 'yes' or 'no')"
            exit 1
          fi
        shell: bash
      - name: Check input
        run: |
          if [[ (${{ inputs.read-only }} != "yes") && (${{ inputs.read-only }} != "no") ]]; then
            echo "::error::'${{ inputs.read-only }}' is not a valid input (should be 'yes' or 'no')"
            exit 1
          fi
        shell: bash
      - name: Get last version
        id: step1
        run: |
          echo "last-version=$(git describe --abbrev=0 | cut -d 'v' -f2)" >> $GITHUB_ENV
          echo "last-version=$(git describe --abbrev=0 | cut -d 'v' -f2)" >> $GITHUB_OUTPUT
          echo "::notice::last-version=$(git describe --abbrev=0 | cut -d 'v' -f2)"
        shell: bash
      - name: Get new version
        id: step2
        run: |
          echo "new-version=$(cat ${{inputs.version-file}})" >> $GITHUB_ENV
          echo "new-version=$(cat ${{inputs.version-file}})" >> $GITHUB_OUTPUT
          echo "::notice::new-version=$(cat ${{inputs.version-file}})"
        shell: bash
      - name: End for read-only
        if: ${{ inputs.read-only }} == "yes"
        run: exit 0
        shell: bash
      - name: Check version file is valid
        run: |
          if ! [[ ${{ env.new-version }} =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
            echo "::error::'${{ env.new-version }}' is not a valid SemVer version format"
            exit 1
          fi
        shell: bash
      - name: Error if version is not new
        run: |
          MAJOR_LAST=$(echo ${{ env.last-version }} | cut -d '.' -f1)
          MINOR_LAST=$(echo ${{ env.last-version }} | cut -d '.' -f2)
          PATCH_LAST=$(echo ${{ env.last-version }} | cut -d '.' -f3)
          MAJOR_NEW=$(echo ${{ env.new-version }} | cut -d '.' -f1)
          MINOR_NEW=$(echo ${{ env.new-version }} | cut -d '.' -f2)
          PATCH_NEW=$(echo ${{ env.new-version }} | cut -d '.' -f3)
          IS_NEW=true
          if [[ $MAJOR_NEW -lt $MAJOR_LAST ]]; then
            IS_NEW=false
          elif [[ $MAJOR_NEW -eq $MAJOR_LAST ]] && [[ $MINOR_NEW -lt $MINOR_LAST ]]; then
            IS_NEW=false
          elif [[ $MAJOR_NEW -eq $MAJOR_LAST ]] && [[ $MINOR_NEW -eq $MINOR_LAST ]] && [[ $PATCH_NEW -le $PATCH_LAST ]]; then
            IS_NEW=false
          fi
          if ! $IS_NEW; then
            echo "last version is:    v${{ env.last-version }}"
            echo "new version is:     v${{ env.new-version }}"
            echo "${{ env.new-version }} <= ${{ env.last-version }}: version not new"
            echo "::error::no new version"
            exit 1
          fi
        shell: bash
      - name: Tag new version
        if: ${{ inputs.check-only == 'no' }}
        run: |
          if ! [[ ${{ inputs.check-only }} != "yes" ]]; then
            echo "::error::'${{ inputs.check-only }}' is not a valid input (should be 'yes' or 'no')"
            exit 1
          fi
          echo "latest version is: v${{ env.last-version }}"
          echo "new version is:    v${{ env.new-version }}"
          echo "publishing new tag..."
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -a v${{ env.new-version }} -m "Realse version ${{ env.new-version }}"
          git push origin v${{ env.new-version }}
          echo "::notice:: new tag published: 'v${{ env.new-version }}'"
        shell: bash
